---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.k8s.svketen.dev
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.k8s.svketen.dev
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.k8s.svketen.dev
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.k8s.svketen.dev
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.k8s.svketen.dev
  resources:
  - spaces/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.k8s.svketen.dev
  resources:
  - spaces/status
  verbs:
  - get
  - patch
  - update
